apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service-deployment
  labels:
    app: client-service-deployment
spec:
  selector:
    matchLabels:
      app: client-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: client-service-deployment
    spec:
      containers:
        - name: client-service
          image: dguerra15/client-service
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_CLIENT_SERVICE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_CLIENT_SERVICE
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_CLIENT_SERVICE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_CLIENT_SERVICE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_CLIENT_SERVICE