Vuelve a revisarmelo todo:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-deployment
  labels:
    app: config-service-deployment
spec:
  selector:
    matchLabels:
      app: config-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: config-service-deployment
    spec:
      containers:
        - name: config-service
          image: dguerra15/config-service
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: config-service  # Este es el nombre DNS que otros servicios usarán
  labels:
    app: config-service
spec:
  selector:
    app: config-service  # Debe coincidir con los labels de tu Pod/Deployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer  # LoadBalancer solo se necesita si se expone hacia afuera