apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentdetail-service-deployment
  labels:
    app: paymentdetail-service-deployment
spec:
  selector:
    matchLabels:
      app: paymentdetail-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: paymentdetail-service-deployment
    spec:
      containers:
        - name: paymentdetail-service
          image: dguerra15/paymentdetail-service
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_PAYMENTDETAIL_SERVICE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_PAYMENTDETAIL_SERVICE
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_PAYMENTDETAIL_SERVICE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_PAYMENTDETAIL_SERVICE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_PAYMENTDETAIL_SERVICE