apiVersion: apps/v1
kind: Deployment
metadata:
  name: specialday-service-deployment
  labels:
    app: specialday-service-deployment
spec:
  selector:
    matchLabels:
      app: specialday-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: specialday-service-deployment
    spec:
      containers:
        - name: specialday-service
          image: dguerra15/specialday-service
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_SPECIALDAY_SERVICE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_SPECIALDAY_SERVICE
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_SPECIALDAY_SERVICE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_SPECIALDAY_SERVICE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_SPECIALDAY_SERVICE